package com.myspace.getting_started;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DTO implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "seleccionado")
	private java.lang.String seleccionado;

	public DTO() {
	}

	public java.lang.String getSeleccionado() {
		return this.seleccionado;
	}

	public void setSeleccionado(java.lang.String seleccionado) {
		this.seleccionado = seleccionado;
	}

	public DTO(java.lang.String seleccionado) {
		this.seleccionado = seleccionado;
	}

}